[package]
name = "pahkat-repomgr"
version = "1.0.0-alpha.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
pahkat-types = { path = "../pahkat-types" }
tokio = { version = "0.2", features = ["net"] }
dialoguer = { version = "0.5.0", optional = true }
termcolor = { version = "1.1.0", optional = true }
url = "2.1.1"
serde = "1.0.106"
serde_json = "1.0.51"
anyhow = "1.0.28"
structopt = { version = "0.3.13", optional = true }
typed-builder = "0.5.1"
thiserror = "1.0.14"
toml = "0.5.6"
log = "0.4.8"
butte = { git = "https://github.com/butte-rs/butte" }
butte-build = { git = "https://github.com/butte-rs/butte" }

[build-dependencies]
anyhow = "1.0.28"
butte-build = { git = "https://github.com/butte-rs/butte" }

[features]
default = ["cli"]
cli = ["dialoguer", "termcolor", "structopt"]
